### ISSUE TITLE
Hero Image 1 Screener

### ISSUE THREAD

**Issue by CryptoPrism-io** [CryptoPrism-io/CryptoPrism-DB#2]
Reference Images to build upon 

 ![Image](https://github.com/user-attachments/assets/7fa01f8d-fe0f-407d-b767-03cc394db28b)
![Image](https://github.com/user-attachments/assets/8a84ff90-87f4-4576-95c5-d15441f5f064)

Top things to show in screener 
1. We have Multiple screeners
2. We have text to sql search
3. We have DMV for easier understanding of market data 

Sample Layout
![Image](https://github.com/user-attachments/assets/c7411a01-092a-4ea2-84a9-da2b4cca4047)

filters .. Trading view sample
text to sql on screener.in
left pane altfins sample

**Comment by Skywalker1080** [comment]
![Image](https://github.com/user-attachments/assets/d0edd6ba-47a6-4991-9f79-3be6f140e243)

**Comment by Skywalker1080** [comment]
![Image](https://github.com/user-attachments/assets/b687d308-776f-4b21-9d6f-ff79a381e230)
**Final Draft Home Image 1 Screener**
